apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mostly-ai
  region: eu-central-1

nodeGroups:
  - name: mostly-ai-nodegroup
    instanceType: m5.4xlarge
    desiredCapacity: 1

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator", "controllerManager"]

addons:
  - name: aws-ebs-csi-driver
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
