name: mostlyai-docs on-push workflow

on:
  push:

jobs:
  # pre-commit-linting:
  #   uses: ./.github/workflows/lint-check.yaml
  #   secrets: inherit
  build-docker-image:
    # needs: [pre-commit-linting]
    secrets: inherit
    uses: ./.github/workflows/build-docker-image.yaml
